stages:
  - prepare
  - test
  - publish

.yarn_template: &yarn_definition
  image: cookielab/nodejs:$NODE_VERSION
  stage: prepare
  tags:
    - docker
  script:
    - yarn --ignore-scripts
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - node_modules
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules

'yarn 10/12':
  <<: *yarn_definition
  variables:
    NODE_VERSION: 10

'yarn 12/12':
  <<: *yarn_definition
  variables:
    NODE_VERSION: 12

.lint_template: &lint_definition
  image: cookielab/nodejs:$NODE_VERSION
  stage: test
  tags:
    - docker
  script:
    - bin/lint

'lint 10/12':
  <<: *lint_definition
  dependencies:
    - 'yarn 10/12'
  variables:
    NODE_VERSION: 10

'lint 12/12':
  <<: *lint_definition
  dependencies:
    - 'yarn 12/12'
  variables:
    NODE_VERSION: 12

.typescript_template: &typescript_definition
  image: cookielab/nodejs:$NODE_VERSION
  stage: test
  tags:
    - docker
  script:
    - bin/typescript

'typescript 10/12':
  <<: *typescript_definition
  dependencies:
    - 'yarn 10/12'
  variables:
    NODE_VERSION: 10

'typescript 12/12':
  <<: *typescript_definition
  dependencies:
    - 'yarn 12/12'
  variables:
    NODE_VERSION: 12

.test_template: &test_definition
  image: cookielab/nodejs:$NODE_VERSION
  stage: test
  tags:
    - docker
  services:
    - postgres
  script:
    - bin/jest --coverage --ci --reporters=default --reporters=jest-junit
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      junit: junit.xml

'test 10/12':
  <<: *test_definition
  dependencies:
    - 'yarn 10/12'
  variables:
    NODE_VERSION: 10
    POSTGRES_PASSWORD: toor
    POSTGRES_DB: postgres_client
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
    DATABASE_PASSWORD: toor
    DATABASE_NAME: postgres_client

'test 12/12':
  <<: *test_definition
  dependencies:
    - 'yarn 12/12'
  variables:
    NODE_VERSION: 12
    POSTGRES_PASSWORD: toor
    POSTGRES_DB: postgres_client
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
    DATABASE_PASSWORD: toor
    DATABASE_NAME: postgres_client

publish:
  image: cookielab/nodejs:12
  stage: publish
  tags:
    - docker
  before_script:
    - echo "$NPMRC" > ~/.npmrc
  script:
    - npm version "$CI_COMMIT_TAG" --no-git-tag-version --allow-same-version
    - npm publish --verbose
  only:
    - tags
