stages:
  - prepare
  - test
  - publish

yarn:
  stage: prepare
  tags:
    - docker
  image: cookielab/nodejs:8
  script:
    - yarn
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - node_modules
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 day
    paths:
      - node_modules

lint:
  stage: test
  tags:
    - docker
  dependencies:
    - yarn
  image: cookielab/nodejs:8
  script:
    - bin/lint

flow:
  stage: test
  tags:
    - docker
  dependencies:
    - yarn
  image: cookielab/nodejs:8
  script:
    - bin/flow

test:
  stage: test
  tags:
    - docker
  dependencies:
    - yarn
  services:
    - postgres
  image: cookielab/nodejs:8
  variables:
    REDIS_HOST: localhost
    POSTGRES_PASSWORD: toor
    POSTGRES_DB: postgres_client
    DATABASE_HOST: localhost
    DATABASE_USER: postgres
    DATABASE_PASSWORD: toor
    DATABASE_NAME: postgres_client
  script:
    - bin/jest --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

publish:
  stage: publish
  tags:
    - docker
  image: cookielab/nodejs:8
  script:
    - bin/build
    - npm version "$CI_COMMIT_TAG" --no-git-tag-version
    - npm publish --verbose
  only:
    - tags
