stages:
  - prepare
  - test
  - publish

.node_8_template: &node_8_definition
  image: cookielab/nodejs:8
  variables:
    NODE_VERSION: 8

.node_10_template: &node_10_definition
  image: cookielab/nodejs:build-10
  variables:
    NODE_VERSION: 10

.yarn_template: &yarn_definition
  stage: prepare
  tags:
    - docker
  script:
    - yarn
  cache:
    key: "$NODE_VERSION:$CI_JOB_NAME"
    paths:
      - node_modules
  artifacts:
    name: "$NODE_VERSION:$CI_JOB_NAME"
    expire_in: 1 day
    paths:
      - node_modules

yarn-8:
  <<: *node_8_definition
  <<: *yarn_definition

yarn-10:
  <<: *node_10_definition
  <<: *yarn_definition

.lint_template: &lint_definition
  stage: test
  tags:
    - docker
  script:
    - bin/lint

lint-8:
  <<: *node_8_definition
  <<: *lint_definition
  dependencies:
    - yarn-8

lint-10:
  <<: *node_10_definition
  <<: *lint_definition
  dependencies:
    - yarn-10

.flow_template: &flow_definition
  stage: test
  tags:
    - docker
  script:
    - bin/flow

flow-8:
  <<: *node_8_definition
  <<: *flow_definition
  dependencies:
    - yarn-8

flow-10:
  <<: *node_10_definition
  <<: *flow_definition
  dependencies:
    - yarn-10

.test_template: &test_definition
  stage: test
  tags:
    - docker
  dependencies:
    - yarn
  services:
    - postgres
  variables:
    POSTGRES_PASSWORD: toor
    POSTGRES_DB: postgres_client
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
    DATABASE_PASSWORD: toor
    DATABASE_NAME: postgres_client
  script:
    - bin/jest --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

test-8:
  <<: *node_8_definition
  <<: *test_definition
  dependencies:
    - yarn-8

test-10:
  <<: *node_10_definition
  <<: *test_definition
  dependencies:
    - yarn-10

publish:
  <<: *node_10_definition
  stage: publish
  tags:
    - docker
  before_script:
    - echo "$NPMRC" > ~/.npmrc
  script:
    - npm version "$CI_COMMIT_TAG" --no-git-tag-version --allow-same-version
    - npm publish --verbose
  only:
    - tags
