stages:
  - prepare
  - test
  - publish

.yarn_template: &yarn_definition
  image: cookielab/nodejs:$NODE_VERSION
  stage: prepare
  tags:
    - docker
  script:
    - yarn
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - node_modules
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules

'yarn 8/10':
  <<: *yarn_definition
  variables:
    NODE_VERSION: 8

'yarn 10/10':
  <<: *yarn_definition
  variables:
    NODE_VERSION: 10

.lint_template: &lint_definition
  image: cookielab/nodejs:$NODE_VERSION
  stage: test
  tags:
    - docker
  script:
    - bin/lint

'lint 8/10':
  <<: *lint_definition
  dependencies:
    - 'yarn 8/10'
  variables:
    NODE_VERSION: 8

'lint 10/10':
  <<: *lint_definition
  dependencies:
    - 'yarn 10/10'
  variables:
    NODE_VERSION: 10

.flow_template: &flow_definition
  image: cookielab/nodejs:$NODE_VERSION
  stage: test
  tags:
    - docker
  script:
    - bin/flow

'flow 8/10':
  <<: *flow_definition
  dependencies:
    - 'yarn 8/10'
  variables:
    NODE_VERSION: 8

'flow 10/10':
  <<: *flow_definition
  dependencies:
    - 'yarn 10/10'
  variables:
    NODE_VERSION: 10

.test_template: &test_definition
  image: cookielab/nodejs:$NODE_VERSION
  stage: test
  tags:
    - docker
  services:
    - postgres
  script:
    - bin/jest --coverage --ci --reporters=default --reporters=jest-junit
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      junit: junit.xml

'test 8/10':
  <<: *test_definition
  dependencies:
    - 'yarn 8/10'
  variables:
    NODE_VERSION: 8
    POSTGRES_PASSWORD: toor
    POSTGRES_DB: postgres_client
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
    DATABASE_PASSWORD: toor
    DATABASE_NAME: postgres_client

'test 10/10':
  <<: *test_definition
  dependencies:
    - 'yarn 10/10'
  variables:
    NODE_VERSION: 10
    POSTGRES_PASSWORD: toor
    POSTGRES_DB: postgres_client
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
    DATABASE_PASSWORD: toor
    DATABASE_NAME: postgres_client

publish:
  image: cookielab/nodejs:10
  stage: publish
  tags:
    - docker
  before_script:
    - echo "$NPMRC" > ~/.npmrc
  script:
    - npm version "$CI_COMMIT_TAG" --no-git-tag-version --allow-same-version
    - npm publish --verbose
  only:
    - tags
